import { neon, types, type NeonQueryFunction } from '@neondatabase/serverless';

const PG_INT8_OID = 20;
const PG_FOREIGN_KEY_VIOLATION = '23503';
const PG_UNIQUE_VIOLATION = '23505';

types.setTypeParser(PG_INT8_OID, (value: string) => Number(value));

const toPgPlaceholders = (sql: string): string => {
  let out = '';
  let index = 0;
  let i = 0;

  while (i < sql.length) {
    const char = sql[i];

    if (char === "'") {
      out += char;
      i += 1;
      while (i < sql.length) {
        out += sql[i];
        if (sql[i] === "'") {
          if (sql[i + 1] === "'") {
            out += sql[i + 1];
            i += 2;
            continue;
          }
          i += 1;
          break;
        }
        i += 1;
      }
      continue;
    }

    if (char === '-' && sql[i + 1] === '-') {
      const lineEnd = sql.indexOf('\n', i);
      const stop = lineEnd === -1 ? sql.length : lineEnd;
      out += sql.slice(i, stop);
      i = stop;
      continue;
    }

    if (char === '?') {
      index += 1;
      out += `$${index}`;
      i += 1;
      continue;
    }

    out += char;
    i += 1;
  }

  return out;
};

const splitStatements = (sql: string): string[] =>
  sql
    .split(';')
    .map((statement) => statement.trim())
    .filter((statement) => statement.length > 0);

export interface RunResult {
  rowCount: number;
}

export interface Database {
  get<T = any>(query: string, params?: unknown[]): Promise<T | undefined>;
  all<T = any>(query: string, params?: unknown[]): Promise<T[]>;
  run(query: string, params?: unknown[]): Promise<RunResult>;
  exec(sql: string): Promise<void>;
  close(): Promise<void>;
}

let client: NeonQueryFunction<false, true> | undefined;
let db: Database | undefined;

const SCHEMA = `
CREATE TABLE IF NOT EXISTS users (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  email       TEXT NOT NULL UNIQUE,
  password    TEXT NOT NULL,
  role        TEXT NOT NULL,
  status      TEXT NOT NULL DEFAULT 'active',
  area        TEXT NOT NULL DEFAULT 'Avenues',
  phone       TEXT,
  address     TEXT,
  employee_id TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_users_role ON users (role);
CREATE INDEX IF NOT EXISTS idx_users_status ON users (status);
CREATE INDEX IF NOT EXISTS idx_users_area ON users (area);

CREATE TABLE IF NOT EXISTS faults (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id       INTEGER REFERENCES users(id),
  technician_id     INTEGER REFERENCES users(id),
  status            TEXT NOT NULL DEFAULT 'Reported',
  address           TEXT NOT NULL,
  category          TEXT NOT NULL,
  priority          TEXT NOT NULL DEFAULT 'Medium',
  description       TEXT,
  area              TEXT,
  reported_date     TIMESTAMPTZ NOT NULL DEFAULT now(),
  assigned_date     TIMESTAMPTZ,
  resolved_date     TIMESTAMPTZ,
  fault_number      TEXT UNIQUE,
  gps_location      JSONB,
  photos            JSONB,
  signature         JSONB,
  resolution_data   JSONB,
  customer_feedback JSONB
);

CREATE INDEX IF NOT EXISTS idx_faults_customer_id ON faults (customer_id);
CREATE INDEX IF NOT EXISTS idx_faults_technician_id ON faults (technician_id);
CREATE INDEX IF NOT EXISTS idx_faults_status ON faults (status);
CREATE INDEX IF NOT EXISTS idx_faults_category ON faults (category);
CREATE INDEX IF NOT EXISTS idx_faults_priority ON faults (priority);
CREATE INDEX IF NOT EXISTS idx_faults_reported_date ON faults (reported_date DESC);

CREATE TABLE IF NOT EXISTS load_shedding_schedules (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area               TEXT NOT NULL,
  start_time         TEXT NOT NULL,
  end_time           TEXT NOT NULL,
  date               TEXT NOT NULL,
  status             TEXT NOT NULL DEFAULT 'Scheduled',
  reason             TEXT,
  affected_customers INTEGER DEFAULT 0,
  alternative_supply BOOLEAN DEFAULT false,
  notes              TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_schedules_status ON load_shedding_schedules (status);
CREATE INDEX IF NOT EXISTS idx_schedules_area ON load_shedding_schedules (area);
CREATE INDEX IF NOT EXISTS idx_schedules_date ON load_shedding_schedules (date);

CREATE TABLE IF NOT EXISTS fault_reports (
  id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id              INTEGER REFERENCES users(id),
  customer_name            TEXT,
  customer_email           TEXT,
  customer_phone           TEXT,
  area                     TEXT,
  address                  TEXT,
  category                 TEXT,
  priority                 TEXT,
  description              TEXT,
  reported_date            TIMESTAMPTZ NOT NULL DEFAULT now(),
  status                   TEXT DEFAULT 'Reported',
  assigned_technician_id   INTEGER REFERENCES users(id),
  assigned_technician_name TEXT,
  admin_notes              TEXT,
  estimated_resolution_time TEXT,
  actual_resolution_time   TEXT,
  gps_location             JSONB,
  photos                   JSONB
);

CREATE INDEX IF NOT EXISTS idx_fault_reports_customer_id ON fault_reports (customer_id);
CREATE INDEX IF NOT EXISTS idx_fault_reports_technician_id ON fault_reports (assigned_technician_id);

CREATE TABLE IF NOT EXISTS requests (
  id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  applicant_id         INTEGER REFERENCES users(id),
  department           TEXT,
  address              TEXT,
  license_type         TEXT,
  description          TEXT,
  requested_date       TIMESTAMPTZ NOT NULL DEFAULT now(),
  status               TEXT NOT NULL DEFAULT 'Pending',
  admin_notes          TEXT,
  assigned_inspector_id INTEGER REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_requests_applicant_id ON requests (applicant_id);
CREATE INDEX IF NOT EXISTS idx_requests_inspector_id ON requests (assigned_inspector_id);

CREATE TABLE IF NOT EXISTS licenses (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  applicant_id INTEGER REFERENCES users(id),
  inspector_id INTEGER REFERENCES users(id),
  status       TEXT NOT NULL DEFAULT 'Pending',
  address      TEXT,
  license_type TEXT,
  description  TEXT,
  department   TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
`;

export const ensureSchema = async (): Promise<Database> => {
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) {
    throw new Error('DATABASE_URL is not set. Add your Neon connection string to the environment.');
  }

  client = neon(connectionString, { fullResults: true });

  db = {
    get: async <T = any>(query: string, params: unknown[] = []): Promise<T | undefined> => {
      const result = await client!.query(toPgPlaceholders(query), params as any[]);
      return result.rows[0] as T | undefined;
    },
    all: async <T = any>(query: string, params: unknown[] = []): Promise<T[]> => {
      const result = await client!.query(toPgPlaceholders(query), params as any[]);
      return result.rows as T[];
    },
    run: async (query: string, params: unknown[] = []): Promise<RunResult> => {
      const result = await client!.query(toPgPlaceholders(query), params as any[]);
      return { rowCount: result.rowCount ?? 0 };
    },
    exec: async (sql: string): Promise<void> => {
      for (const statement of splitStatements(sql)) {
        await client!.query(statement);
      }
    },
    close: async (): Promise<void> => {
      client = undefined;
      db = undefined;
    },
  };

  await db.exec(SCHEMA);

  return db;
};

export const initDb = async (): Promise<Database> => {
  const db = await ensureSchema();

  const bcrypt = await import('bcryptjs');
  const admin = await db.get('SELECT id FROM users WHERE email = ?', ['admin@zesa.co.zw']);
  if (!admin) {
    const hashedPassword = await bcrypt.hash('admin123', 10);
    await db.run(
      'INSERT INTO users (name, email, password, role, area, status) VALUES (?, ?, ?, ?, ?, ?)',
      ['System Admin', 'admin@zesa.co.zw', hashedPassword, 'Admin', 'Avenues', 'active']
    );
    console.log('Default admin user created: admin@zesa.co.zw / admin123');
  }

  return db;
};

export const getDb = (): Database | undefined => db;

export const isForeignKeyViolation = (error: unknown): boolean =>
  Boolean(error) && (error as { code?: string }).code === PG_FOREIGN_KEY_VIOLATION;

export const isUniqueViolation = (error: unknown): boolean =>
  Boolean(error) && (error as { code?: string }).code === PG_UNIQUE_VIOLATION;
